service: silicron

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - '!**'
    - 'main.py'
    - 'backend/**'
    - 'templates/**'

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: silicron-layer
      description: Silicron layer
      compatibleRuntimes:
        - python3.8

functions:
  app:
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}
