service: silicron

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: silicron-layer
      description: Silicron layer
      compatibleRuntimes:
        - python3.8

functions:
  app:
    package:
      patterns:
        - 'main.py'
        - "!requirements.txt"
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!.virtualenv/**"
        - "!node_modules/**"

    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}